title = "Stably Discordant Server Configuration"

[auth]
discord_token="XXX"

[discord.settings]
# Set channels that the bot listens and responds on. Specify in case-sensitive "[server:channel, server:channel]" format.
# If both are set, only listen_channels is used. If neither are set, the bot will listen on all channels to which it is invited.
listen_channels = []
ignore_channels = []

# Set users that the bot listens and responds to. Specify in case-sensitive "[username#id, username#id]" format.
# Note that after the Discord username change(https://discord.com/blog/usernames) the format is likely to be `username#0`.
# It used to be the case that "id" referred to the (now deprecated) discriminant.
# If both are set, only listen_users is used. If neither are set, the bot will listen to all members, but never itself.
listen_users = []
ignore_users = []

wake_word = "/art"

[discord.style]
ack_emoji = "ğŸ‘"
in_prog_emoji = "â±ï¸"
done_emoji = "ğŸ’¯"

[misc_settings]
log_dir="logs"
